language: node_js
branches:
  only:
  - master
  - stage
services:
  - docker
before_install:
- docker pull <name>
- docker run -d -p 127.0.0.1:80:4567 <name> /bin/sh -c "cd <path>; bundle exec foreman start;"
- docker ps -a
- docker run <name> /bin/sh -c "cd <path>; bundle exec rake test"
script:
- "npm run test"
- "npm run lint"