language: node_js
services:
- docker
jobs:
  include:
    - stage: build
      script: sh ./scripts/build.sh
    # - stage: test
    #   script: sh ./scripts/test.sh
    # - stage: deploy
    #   script: sh ./scripts/deploy.sh

# before_install:
# - docker build -t cybercuffs/woolly:woo .
# - docker run -d -p 80:8080 --name  woo cybercuffs/woolly:woo
# - docker exec -it woo /bin/sh -c "cd tests; go test"
# script:
# - docker ps | grep -q woo
# deploy:
#   provider: script
#   script: bash deploy.sh
#   on:
#     branch: master